from table import Table
from wheel import Wheel
from players.player import Player
from players.martingale import Martingale
from players.cancellation import PlayerCancellation
from players.fibonacci import PlayerFibonacci
from players.seven_reds import SevenReds
from players.random import PlayerRandom
from players.passenger57 import Passenger57
from players.player1326.player1326 import Player1326
